### ISSUE TITLE
Release Management

### ISSUE THREAD

**Issue by ahankinson** [ruven/iipsrv#112]
We're using IIP in a production environment, and are looking at our options for updating our deployment now. Currently we're on 1.0, and want to patch our systems to incorporate a few critical fixes (e.g., #88). At the same time, I've been following the `master` branch, and while there are some exciting things in the pipeline, I'm not sure about deploying these to our production systems just yet. So our options seem to be either `a)` build from master, `b)` build a quite outdated release, or `c)` pick an arbitrary point in the commit history and deploy from that. At the moment we're contemplating `c)`, but it would be nice if this was a bit more formalized.

How stable can we expect the `master` branch to be? Is there any interest in moving new feature developments to a `develop` branch, and having `master` be the most recent "stable" version, with critical fixes applied?

**Comment by beaudet** [comment]
+1 for develop branch

**Comment by ruven** [comment]
OK, I've just created a develop branch. The master branch is intended to be well-tested stable code that should be usable in production environments. All major new features should now target this new branch rather than master.

Apart from minor new features and bug fixes, the only major new code in the master branch at the moment is the experimental OpenJPEG support. As this component is very modular and, in any case, only compiled conditionally, I think it's safe to consider the current master branch as production-ready. Please let me know if there's anything you consider too risky within master.

**Comment by ahankinson** [comment]
OK, great! Thanks so much.
