### ISSUE TITLE
Feature to set kakadu's fussy/resilient/fast error handling mode

### ISSUE THREAD

**Issue by jothomp-dev** [ruven/iipsrv#122]
Hi Ruven,

I have some JP2 images that are malformed in such a way that kakadu's `kdu_codestream::set_fast` error handling mode causes the decoding to fail.  The decoding does not fail, however, when using `kdu_codestream::set_resilient`.  I am wondering if it would be useful to anyone else if iipsrv included some configuration option to set how kakadu handles errors?

I have an example here where I've added an environment variable called `ERROR_MODE`.  I don't know if this is the best way to add support for this feature, or how useful it is to anyone else:
https://github.com/jothomp-dev/iipsrv/commit/799e7969b895fe01b54617a04c6553576fa6f705

Do you think this is a reasonable feature to add?

Thanks,
John

**Comment by ruven** [comment]
Does the decoding fail when loading JP2 metadata or only for the image data itself? If already for the metadata, we could include an initial try ... catch block which could test for this.

**Comment by jothomp-dev** [comment]
I'm afraid I don't know.  This is the error message I get in the log:

> Full Request is IIIF=/service/gmd/gmdlva/glva/glva01/lva00119.jp2/full/pct:15/0/default.jpg
> [1/1]: Command / Argument is IIIF : /service/gmd/gmdlva/glva/glva01/lva00119.jp2/full/pct:15/0/default.jpg
> IIIF handler reached
> IIIF :: URL decoded to /service/gmd/gmdlva/glva/glva01/lva00119.jp2/full/pct:15/0/default.jpg
> FIF handler reached
> FIF :: URL decoding/filtering: /service/gmd/gmdlva/glva/glva01/lva00119.jp2 => /service/gmd/gmdlva/glva/glva01/lva00119.jp2
> FIF :: Image cache initialization
> FIF :: JPEG2000 image detected
> FIF :: Created image
> FIF :: Image dimensions are 8208 x 5741
> FIF :: Image contains 3 channels with 8 bits per channel
> FIF :: Image timestamp: Sat, 07 May 2005 15:32:31 GMT
> FIF :: Total command time 13577 microseconds
> IIIF :: Requested Region: x:0, y:0, w:1, h:1
> IIIF :: Requested Size: 1231x861
> IIIF :: Requested Rotation: 0 degrees
> IIIF :: Requested Quality: default with format: jpg
> IIIF :: image request for /service/gmd/gmdlva/glva/glva01/lva00119.jp2 with arguments: region: 0,0,8208,5741; size: 1231x861; rotation: 0; mirroring: 0
> CVT handler reached
> CVT :: Using resolution 3 with size 2052x1435
> CVT :: No view port set
> CVT :: Requested scaled region size is 1231x861 at resolution 3. Nearest existing resolution has region with size 2052x1435
> TileManager getRegion :: requesting region directly from image
> Kakadu Core Error:
> Encountered a corrupted packet while using packet length information to access
> the compressed data source in a random access fashion.  To process corrupted
> code-streams in an error resilient manner, you must disable seeking on the
> compressed data source (i.e., force sequential access) as well as enabling the
> resilient parsing mode.
> Kakadu :: Core Exception Caught
> Sending HTTP 404 Not Found
> Total Request Time: 393544 microseconds
> image closed and deleted
> Server count is 1

And the JP2 can be found here:
https://cdn.loc.gov/service/gmd/gmdlva/glva/glva01/lva00119.jp2

**Comment by ruven** [comment]
The error is occurring during the image decoding not during reading the metadata. So, yes, maybe your initial suggestion could be useful. If we have an environment variable for this, we should perhaps be more specific and call it JPEG2000_READMODE or just KAKADU_READMODE if this option isn't avaialble in OpenJPEG.

The image itself, however, has a problem and is mal-formed. Why don't you also just fix these broken images in your collection?

**Comment by jothomp-dev** [comment]
I will look into the possibility of fixing the broken images.

In my fork I've renamed the env variable to KAKADU_READMODE:
https://github.com/jothomp-dev/iipsrv/commit/6d87ea992f698f50d968bba73dfc6ca316160759

Should I create a pull request?

**Comment by ahankinson** [comment]
Most of the options in the IIP settings are integers.

**Comment by ruven** [comment]
There's one small issue with your fork, which is that KakaduImage.cc does not include Environment.h, but has a dependency on this so your code will not compile with certain compilers. Indeed, to keep things properly clean and separate, I would like to avoid adding such a dependency to the KakaduImage class. So, perhaps readmode should be made something more generic and included within the IIPImage parent class itself? Or otherwise simply a member variable of the KakaduImage class. The configuration setting could then be read from the environment only once at iipsrv startup and set within the KakaduImage class when the image object is created. This is advantageous as accessing environment variables is surprisingly slow and is better only done once rather than each time an image is opened. Every millisecond counts ;-)

As for using integers, I've tended to use these in other option parameters as they are simpler to handle and avoid spelling errors from users. I guess we could use 0 for fast, 1 for fussy and 2 for resilient?

**Comment by jothomp-dev** [comment]
These are good suggestions.  I'll implement them and get back to you.

**Comment by jothomp-dev** [comment]
Hi Ruven,

I made the changes.  I had to add a virtual function setReadmode to the IIPImage parent class in order to be able to set the readmode on a KakaduImage instance which is referenced through an IIPImage pointer.  And after reading the KAKADU_READMODE environment variable I stored the readmode in the session struct to allow the image to have access to it.  I'm not sure if there is a less intrusive way of doing that.

I also created a vector of "PropertySetters" that gets iterated through when we want to apply some settings to an IIPImage that might differ depending on whether the IIPImage is from kakadu or openjpeg.  I figured this would be a general way of doing things like calling `setReadmode(int)` or other setters but I don't know if it's the best approach.

I did use the 0, 1, 2 settings as you suggested.

Here is what I changed from my previous version:
https://github.com/jothomp-dev/iipsrv/compare/1a4b44913792d274d7ad47ab5ac8ff0e682af182...jothomp-dev:master

**Comment by ruven** [comment]
Thanks for this, it looks great. Just one comment. We can potentially have readmodes for other formats or decoders, so in Main or FIF, the session variable should be Kakadu specific. Maybe this could be an STL map or something which could contain readmodes for the various input formats.

**Comment by jothomp-dev** [comment]
Hi Ruven,
I got busy for a while, but finally added the `session.readmodes` STL map.  Also refactored my code a little.
Here's the comparison with your master branch:
https://github.com/ruven/iipsrv/compare/master...jothomp-dev:master

If everything looks good I'll create a pull request.
Thanks,
John

**Comment by thatcher** [comment]
Hi checking on the status of this.  

Following up on John's earlier notes we may eventually be able to reprocess these JP2 but we have _millions_ of them and they all work with Aware even though Kakadu barfs on some.

We are currently support IIIF with a home grown solution via Aware and its scales ok horizontally but would love to add IIPSrv into the stack for the heavy lifting on tiling because it is faster.

**Comment by ruven** [comment]
I just made a commit (https://github.com/ruven/iipsrv/commit/53b24d339753267819df47964fe88fc62b9b3be5) which adds a KAKADU_READMODE start-up variable, which will allow you to use Kakadu's resilient mode.

Thanks @jothomp-dev, I based it on your suggested changes, but made it more generic so that we can use this mechanism to pass any kind of codec options in the future.
