### ISSUE TITLE
iipsrv.fcgi pre build

### ISSUE THREAD

**Issue by ericvanderlinden** [ruven/iipsrv#163]
Is there a iipsrv.fcgi pre build for download somewhere. Every way I try to build from the readme info I get errors and tools missing. 
I really just want to run the server... I'm a front end developer and do not have the skills to understand the build proces I think.

**Comment by ruven** [comment]
For which platform? There are binaries for Windows, Mac OS X and Solaris available for download. For Linux, if you're using a distribution such as Debian, Ubuntu, Fedora, CentOS etc, iipsrv is included in the system package manager.

**Comment by ericvanderlinden** [comment]
Ubuntu... Sorry I should have mentioned it, my hosting company where I have a virtual server did not include it in package manager.
If it is just as simple as copying iipsrv.fcgi in the fcgi folder... Is there a download of iipsrv.fcgi available somewhere.

**Comment by ruven** [comment]
On Ubuntu, you should be able to just do:

`apt-get install iipimage-server`

Otherwise you can download the deb file (which includes the binary) built for your architecture directly here for Ubuntu 18.10:
[https://packages.ubuntu.com/cosmic/iipimage-server](https://packages.ubuntu.com/cosmic/iipimage-server)

Install using `dpkg -i <debfile.deb>`, then `apt-get install -f ` if there are missing dependencies

Alternatively to build yourself, you only need 3 dependencies which you can install like this:

`apt-get install zlib1g-dev libtiff5-dev libturbojpeg-dev`

**Comment by ericvanderlinden** [comment]
Thank you. I will try your suggestions.
