### ISSUE TITLE
how to limit file sizes to save bandwidth, but let IIP/IIIF client viewers work as usual

### ISSUE THREAD

**Issue by abubelinha** [ruven/iipsrv#204]
Not a bug. 
Just asking for previous advice before downloading and installing.
I need to know if this configuration could be possible.

I want to use the server for providing image access, but I need to put certain limits:
- I have a limited bandwidth usage.
- So I don't want users be able to download/hotlink full sized images
- But I want to let them use iipmooviewer (or any IIIF compliant viewer)

I suppose [`MAX_CVT` server startup variable](https://iipimage.sourceforge.io/documentation/server/) is the way to go.
But I also want my server be [IIIF compliant](https://iipimage.sourceforge.io/2014/12/iiif/).
Would `MAX_CVT` configuration be enough to stop server returning high `size` requests?

How does this affect clients like iipmooviewer using IIIF protocol?
My MAX_CVT would be much bigger than tile sizes, but I wonder if iiipmooviewer would be using tiles or not.

BTW, I ask this because I am not being able to look at the example here (so I could look which kind of images are requested by client):
http://merovingio.c2rmf.cnrs.fr/iipimage/iipmooviewer/iiif.html

I guess some https problems, although my Chrome browser is up to date: Version 88.0.4324.104 (Official Build) (64-bit)

**Comment by ahankinson** [comment]
`MAX_CVT` is what you want; it will be IIIF-compliant, since it advertises the max requestable image in the info.json. (This was a bug that was fixed last year, so it should actually work now!)

See: https://github.com/ruven/iipsrv/issues/157

A MAX_CVT of 1000px is generally acceptable. Remember that's 1000px in the largest dimension, so if your image is 2000x1000, it will return a 1000x500 image.

The problem with the example image you linked to is that the JS is failing to parse the info.json; the array is `sizes` but it's trying to find them in `size`.

**Comment by abubelinha** [comment]
> The problem with the example image you linked to is that the JS is failing to parse the info.json; the array is `sizes` but it's trying to find them in `size`.

I hope @ruven can fix the example or provide another one.
Thanks a lot.

**Comment by ruven** [comment]
OK, fixed the iipmooviewer demo: [https://merovingio.c2rmf.cnrs.fr/iipimage/iipmooviewer/iiif.html](https://merovingio.c2rmf.cnrs.fr/iipimage/iipmooviewer/iiif.html)

 > My MAX_CVT would be much bigger than tile sizes, but I wonder if iiipmooviewer would be using tiles or not.

Yes, IIPMooviewer (and most other viewers) use tiles, so are not affected by the MAX_CVT limit.

**Comment by abubelinha** [comment]
> Yes, IIPMooviewer (and most other viewers) use tiles, so are not affected by the MAX_CVT limit.

Thanks a lot @ruven !

I am wondering: when iipmooviewer client works “in IIIF mode”, does it actually keep requesting the same tiles as in “normal mode”, but using IIIF-styled urls?

In that case I can safely use a lower MAX_CVT value, like 256 or so. Correct?
Would I need to adjust the client configuration for that, or server itself tells clients about correct tile size to request?

**Comment by ahankinson** [comment]
I would be cautious about setting MAX_CVT too low... I don't think you will actually save *that* much bandwidth over a slightly higher value, and instances where larger single-image sizes are used (I'm thinking mostly the 'grid view' of Universal Viewer) your images will look pretty bad and be almost unusable for people to distinguish which pages are the one they're looking for. Most IIIF clients default to tile requests anyway, so that's where the bulk of your traffic will come from.

There are other ways of optimizing access as well. The `JPEG_QUALITY` setting can be lowered to reduce bandwidth across the board. If you're worried about too many requests overwhelming your server, you can configure a caching layer up front with nginx to reduce the load on your image processing system. You can also layer the various caches (frontend, memcached, iip's internal cache) to provide varying levels of persistence so that IIP only processes the images as a last resort.

**Comment by abubelinha** [comment]
Thanks a lot for the advices.

> I'm thinking mostly the 'grid view' of Universal Viewer

I actually came here because I was planning to upgrade a very old combination of iipsrv-, and I discovered its IIIF support.
I didn’t knew Universal Viewer. Can you pass me any example links to that grid view you mention?

**Comment by ahankinson** [comment]
Sure! 

https://universalviewer.io

It's hard to link to the grid view directly, but if you go here:

https://iiif.bodleian.ox.ac.uk/iiif/viewer/03800c8f-a492-4efd-b13a-7a20c8c24b34

and then click on the four squares in the upper-right corner, then you'll see the 'grid view'. You can then adjust the size of individual images using the slider. 

Mirador (https://projectmirador.org) has similar features. There are a number of other IIIF-compatible image viewers as well. https://iiif.io/apps-demos/#image-viewing-clients

**Comment by abubelinha** [comment]
OK, I understand what you meant.

Those "full page previews" in the grid, are single IIIF requests to show the full image at a given size.
In that example, when I move the slider to their biggest size, the images are requested at 200 width size
As that results in a images which are 200 x 266 (which could not be nice if my MAX_CVT is 256).

Thanks a lot for the links !

**Comment by ruven** [comment]
>I am wondering: when iipmooviewer client works “in IIIF mode”, does it actually keep requesting the same tiles as in “normal mode”, but using IIIF-styled urls?

Basically yes. The viewer makes IIIF requests based on the available tile sizes given in the info.json file and the server detects whether an IIIF request is exactly mapped to a physical tile within your TIFF file.

**Comment by abubelinha** [comment]
Thanks @ruven 
I adapted your IIIF example and tried it with [this image](https://zenodo.org/api/iiif/v2/6d2dbb72-5736-4679-b350-77492092068b:ad623be0-59e3-4468-8927-398573d033c7:BR0000012078165.jpg/full/500,/0/default.jpg), served directly from that link (so, I am not using iipsrv, just iipmooviewer).

It does not work properly. 
Although it loads the tiles, they are wrongly assembled to the right part of the viewer (i.e., there are a "cuts" in the viewer, one vertical and another one horizontal). 

I am trying it in localhost. Could you try it yourself?
These are the only things you need to change in `iiif.html`:

```
var server = "https://zenodo.org/api/iiif/v2/";
var image = '6d2dbb72-5736-4679-b350-77492092068b:ad623be0-59e3-4468-8927-398573d033c7:BR0000012078165.jpg';
```
Plus I touched `iiif.js` file and replaced the strings _native.jpg_ by _default.jpg_, since that server uses IIIF 2 [quality](https://iiif.io/api/image/2.0/#quality)

**Comment by ahankinson** [comment]
You're missing quite a few fields in the info.json response:

https://zenodo.org/api/iiif/v2/6d2dbb72-5736-4679-b350-77492092068b:ad623be0-59e3-4468-8927-398573d033c7:BR0000012078165.jpg/info.json

Compare with:

https://iiif.rism.digital/image/lausanne/Gc_prg/CH_Gc_prg_14/pyr_CH_Gc_prg_14-0993.tif/info.json

Different clients look at different data in the info response, so just because one client can use the data you provide doesn't mean that they all can.

**Comment by abubelinha** [comment]
Thanks again @ahankinson
Very informative indeed, although a bit too technical for me, I'm afraid.

So, the info.json returned by zenodo server is wrong?
I mean ... is it missing fields which should be there if it was an IIIF 2 compliant server?

But in that case, perhaps clients should better recognize this missing info, and stop trying to show the image. 
i.e., showing a "wrong info.json file, not an IIIF-compliant server" message or something like that, would be a better choice than showing a distorted image.

Or maybe I am just misunderstanding your comment about info.json

**Comment by ahankinson** [comment]
The `info.json` is created and served by IIP; I'm not sure what your specific setup is, but I'm surprised that it's not just passing that request along to IIP. It's not something you need to construct manually; generally all IIIF image servers will generate this automatically from the image data.

Incidentally, what version of IIP are you using?

The [IIIF Image API v2.1 specification](https://iiif.io/api/image/2.1/) gives more details on the structure. There are different levels of compliance given in that specification. For clients that are coded to handle what the spec says, it's hard to detect the ways that different responses fall outside of the spec, which is why you can get varying responses (from "it works fine" to "it works, but not correctly" to "it doesn't work at all"). 

For example, I notice that your response omits the 'sizes' section of the info.json, which (as we've already seen) the iip moo viewer code looks at for some information. That could be why it's not working correctly for you.

**Comment by abubelinha** [comment]
I think you misunderstood.
I made a [previous comment](https://github.com/ruven/iipsrv/issues/204#issuecomment-771877217) about an old iipsrv-iipmooviewer installation of mine. That's one of the things I'll try but for now I am just playing with the client against other IIIF servers (I still have not upgraded mine, which is 0.9.9).

So, when [I later said I had tested](https://github.com/ruven/iipsrv/issues/204#issuecomment-773258411) @ruven's iipmooviewer example in IIIF mode, I also mentioned I was not connecting to iipsrv, but to a different remote IIIF server, which is not an iipserver. 
It's the server used to produce zenodo.org image previews. 
As it is supposed to be an IIIF compliant server, I expected my test should work.

I have just tried to find out which is the software behind. I think this is it:
https://github.com/inveniosoftware/invenio-iiif

But anyway, I think your last answer explains everything, and for now it is not possible to use iipmooviewer-IIIF against that server.

**Comment by ruven** [comment]
I tried pointing to the Zenodo IIIF end-point with your example image and there are indeed problems with the edge tiles:
[https://merovingio.c2rmf.cnrs.fr/iipimage/iipmooviewer/zenodo-iiif.html](https://merovingio.c2rmf.cnrs.fr/iipimage/iipmooviewer/zenodo-iiif.html).

iipmooviewer should handle these kinds of info.json files better - I'll fix it shortly

**Comment by abubelinha** [comment]
Thanks for trying it, @ruven 

And sorry because this started as an iipsrv-related issue, but then most of the thread derived about iipmooviewer. I should have opened another issue there

**Comment by abubelinha** [comment]
@ruven: I am closing this because my iipsrv questions were addressed long time ago.

The iipmooviewer / Zenodo-IIIF compatibily issue still remains, so I summarized it in [iipmooviewer #80](https://github.com/ruven/iipmooviewer/issues/80).
I hope you can take a look at it since IMHO iipmooviewer would be such a great viewer for Zenodo deposited files.
