### ISSUE TITLE
ProPhoto RGB and PNG output problem

### ISSUE THREAD

**Issue by altert** [ruven/iipsrv#239]
It seems that for sources with ProPhoto RGB icc profile embedded iipimage 1.2 fails to deliver PNG images with profile attached. 
Same image with CVT=JPG is displayed correctly, but with CVT=PNG it fails (silently, nothing in log)
Same problem manifests itself if I'm using IIIF protocol

**Comment by ruven** [comment]
Do you have an example image I could test?

**Comment by altert** [comment]
![_DSF1570](https://user-images.githubusercontent.com/504256/191297470-5de4e244-594a-47ca-a9fd-22c4df013ba3.jpg)
I hope attached file retains profile, if not, I can upload elsewhere

**Comment by altert** [comment]
and here is actual tiled tiff made from previous image that was used as source for iipimage (converted by vips)

**Comment by ruven** [comment]
This was in fact caused by your ProPhoto profile not fully following the ICC specification. The latest version of the libpng library now checks for ICC profile correctness and will reject any that are incorrect. Fortunately, there's a way to disable these checks and I've submitted a fix (https://github.com/ruven/iipsrv/commit/eb00e889f5dac624ae4829c605449cdd74a75116) that should allow your images to work.

**Comment by altert** [comment]
Thank you very much! I've installed new version and it works great. Interestingly, I've assigned prophoto rgb profile using Adobe Photoshop and MacOS preview, that's why I didn't expect malformed profile result.
