### ISSUE TITLE
CORS header not always present

### ISSUE THREAD

**Issue by eduh** [ruven/iipsrv#256]
We have a problem that sometimes the CORS header is missing (we use version 1.2 with cors header set in fcgi vars)

This header is correct and contains the  access-control-allow-origin  *
https://iiif.apps-dev.k8s.library.uu.nl/fcgi-bin/iipsrv.fcgi?IIIF=/manifestation/viewer/12/34/75/123475797878481002619253132838342385263.jp2/0,1024,1024,1024/256,/0/default.jpg

This one is lacking the header
https://iiif.apps-dev.k8s.library.uu.nl/fcgi-bin/iipsrv.fcgi?IIIF=/manifestation/viewer/12/34/75/123475797878481002619253132838342385263.jp2/full/256,/0/default.jpg

We have not any clue. We have nginx as reverse proxy  and experimented with adding  cors-allow-headers and cors-allow-origin stuff but without success

**Comment by ruven** [comment]
In fact, it's because the second URL is for a region, rather than a tile (you're asking for the full image with a width of 256 pixels). These different types are handled differently by iipsrv and it wasn't adding the CORS headers for such requests. I've just pushed a patch that fixes this so that all requests types get the same headers: https://github.com/ruven/iipsrv/commit/b660c604518776a277b80bef0486a39e4d7553ba

Please try it out and let me know if you still have issues.

**Comment by eduh** [comment]
Great. Will give it a go next week.

**Comment by eduh** [comment]
The fix solved the CORS issue. Many Thanks.
