### ISSUE TITLE
basic resolver for IIIF?

### ISSUE THREAD

**Issue by nicolasfranck** [ruven/iipsrv#58]
The current implementation expects the input identifier to be file path.
One can get from an identifier to a real file path with some basic url-rewriting,
when the path is logical:
```
archive.ugent.be:45-58.jp2 => archive/ugent/45/58.jp2
```

But that rewritten path is used in the "@id" of the info.json,
so the user sees the rewritten path.

So the question is:

- Should the "@id" not be derived from the header "X-Forwarded-Host" if exists? The IIPServer always is behind a proxy server, so url-rewriting is always there.
- Should there be some basic resolver in the IIPServer, maybe url-rewriting to make these requests more transparent?

**Comment by ahankinson** [comment]
I have encountered this as well, but being behind a proxy server does not necessarily mean a rewrite is happening; it is possible to directly proxy IIP to `http://example.com/iipsrv.fcgi?IIIF=/srv/images/123/456.jp2/full/full/0/default.jpg` with no rewriting. (This does go against the IIIF recommendation of *not* using query parameters for URL components since it circumvents caching layers).
