### ISSUE TITLE
Zoomify wrong NUMTILES attribute in ImageProperties.xml

### ISSUE THREAD

**Issue by dsecik** [ruven/iipsrv#86]
Hello,
I found out that iipsrv (built from latest code on github) returns different value of NUMTILES attribute in ImageProperties.xml than [zoomify converter](http://www.zoomify.com/free.htm).

iipsrv: 
`<IMAGE_PROPERTIES WIDTH="6488" HEIGHT="8213" NUMTILES="858" NUMIMAGES="1" VERSION="1.8" TILESIZE="256"/>`

zoomify converter:
`<IMAGE_PROPERTIES TILESIZE="256" VERSION="1.8" NUMIMAGES="1" NUMTILES="1169" HEIGHT="8213" WIDTH="6488"/>`

Is it a bug? I couldn't find any specification for ImageProperties.xml.

Thanks

**Comment by ruven** [comment]
In fact iipsrv calculates the number of tiles that exist at the highest resolution like this:

`int ntiles = (int) ceil( (double)width/tw ) * (int) ceil( (double)height/tw );`

Maybe the zoomify converter calculates the number of tiles available in all resolutions? We'd really need some sort of spec to understand. But does this have any practical effect on the zoomify viewers?

**Comment by zabak** [comment]
Probably not. But it might be a good idea to remain compatible.

**Comment by KempWatson** [comment]
Hi - the Zoomify converter sets NUMTILES to the TOTAL number of tiles in the pyramid, which matched all examples of previous Zoomify folders we've seen. Here's what I get:

Zoomify Converter: 1143 tiles, 6 levels

which would correspond to using FLOOR instead of CEILING for downsampling; but by a CEILING calculation, there should be 1171 tiles, and 7 levels - so regardless of the calculation, I can't see where you are getting the 1169 value from. What version of the converter are you using?

**Comment by zabak** [comment]
Hi - we have forgotten to add a link to the image in question and now, after more than a year we could not identify it. You can close the issue.

**Comment by lovasoa** [comment]
Hello ! I was going to report the exact same problem when I found this issue.
Indeed, the official zoomify product sets `NUMTILES` as the total number of tiles in all levels.
I am the author of a tiled image downloader ([dezoomify-rs](https://github.com/lovasoa/dezoomify-rs)) that uses this property to simplify the TileGroup calculations.

Would you accept a pull request fixing this discrepancy between iipsrv and the official zoomify tiler ?

**Comment by lovasoa** [comment]
Since there is no official specification for the zoomify image format, I did some work trying to unscramble the official javascript viewer (distributed as a minified js file).

If anyone is interested, here it is:
https://gist.github.com/lovasoa/a1442d684a6cabb6e7fe790e4f765f02

I did that to check whether the viewer used the provided `NUMTILES` or computed it itself. It turns out that it does both, and compares the results.
